name: Deploy static content to Pages
on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions: # 权限配置正确
  contents: read
  pages: write
  id-token: write

concurrency: # 改进：新部署会取消进行中的任务
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment: # 环境配置正确
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: blog # 显式指定检出目录名称

      # 新增前端工程化流程 ↓↓↓
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: blog/pnpm-lock.yaml # 指定缓存路径

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./blog # 关键修复点：指定子目录

      - name: Build
        run: pnpm run build
        working-directory: ./blog # 保持目录一致
      # 新增前端工程化流程 ↑↑↑

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: blog/dist # 添加子目录前缀

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 版本号降级
